# Generated by Django 5.1 on 2026-05-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='supabase_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
