# Generated by Django 6.0.4 on 2026-05-01 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(choices=[('Activity', 'Activity'), ('Eatery', 'Eatery')], max_length=20)),
                ('sub_category', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('suburb', models.CharField(max_length=100)),
                ('opening_times', models.CharField(blank=True, max_length=255)),
                ('age_range', models.CharField(blank=True, max_length=20)),
                ('cost', models.CharField(blank=True, max_length=20)),
                ('kids_eat_free', models.CharField(blank=True, max_length=50)),
                ('indoor_outdoor', models.CharField(blank=True, max_length=20)),
                ('wheelchair_friendly', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('verify_before_launch', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_venues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['main_category', 'sub_category'], name='venues_venu_main_ca_e50da5_idx'), models.Index(fields=['suburb'], name='venues_venu_suburb_0312ef_idx')],
            },
        ),
    ]
