# Generated by Django 5.1 on 2026-05-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='main_category',
            field=models.CharField(choices=[('Activity', 'Activity'), ('Eatery', 'Places to Eat')], max_length=20),
        ),
    ]
