# Generated by Django 5.1 on 2026-05-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('postcode', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
